name: Send Mail
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send email
      uses: devellany/send-mail@v1.0.2
      with:
          host: smtp.gmail.com
          port: 465
          account: noreply.screen@gmail.com
          password: Testing@22
          sender: devellany
          from: noreply.screen@gmail.com
          subject: Github Actions job result
          body: file://README.md
          attachments: '[{"path":"README.md"}]'
          to: shyam22.co@gmail.com